"""
This type stub file was generated by pyright.
"""

"""The **splunklib.data** module reads the responses from splunkd in Atom Feed
format, which is the format used by most of the REST API.
"""
__all__ = ["load", "record"]
LNAME_DICT = ...
LNAME_ITEM = ...
LNAME_KEY = ...
LNAME_LIST = ...
XNAMEF_REST = ...
XNAME_DICT = ...
XNAME_ITEM = ...
XNAME_KEY = ...
XNAME_LIST = ...
def isdict(name): # -> bool:
    ...

def isitem(name): # -> bool:
    ...

def iskey(name): # -> bool:
    ...

def islist(name): # -> bool:
    ...

def hasattrs(element): # -> bool:
    ...

def localname(xname):
    ...

def load(text, match=...): # -> Record | list[Any] | list[Record | list[Any]] | None:
    """This function reads a string that contains the XML of an Atom Feed, then
    returns the
    data in a native Python structure (a ``dict`` or ``list``). If you also
    provide a tag name or path to match, only the matching sub-elements are
    loaded.

    :param text: The XML text to load.
    :type text: ``string``
    :param match: A tag name or path to match (optional).
    :type match: ``string``
    """
    ...

def load_attrs(element): # -> Record | None:
    ...

def load_dict(element, nametable=...): # -> Record:
    ...

def load_elem(element, nametable=...): # -> tuple[Any, Any | Record | list[Any] | None] | tuple[Any, Record] | tuple[Any, Any | Record | list[Any]]:
    ...

def load_list(element, nametable=...): # -> list[Any]:
    ...

def load_root(element, nametable=...): # -> Record | list[Any]:
    ...

def load_value(element, nametable=...): # -> Record | list[Any] | None:
    ...

class Record(dict):
    """This generic utility class enables dot access to members of a Python
    dictionary.

    Any key that is also a valid Python identifier can be retrieved as a field.
    So, for an instance of ``Record`` called ``r``, ``r.key`` is equivalent to
    ``r['key']``. A key such as ``invalid-key`` or ``invalid.key`` cannot be
    retrieved as a field, because ``-`` and ``.`` are not allowed in
    identifiers.

    Keys of the form ``a.b.c`` are very natural to write in Python as fields. If
    a group of keys shares a prefix ending in ``.``, you can retrieve keys as a
    nested dictionary by calling only the prefix. For example, if ``r`` contains
    keys ``'foo'``, ``'bar.baz'``, and ``'bar.qux'``, ``r.bar`` returns a record
    with the keys ``baz`` and ``qux``. If a key contains multiple ``.``, each
    one is placed into a nested dictionary, so you can write ``r.bar.qux`` or
    ``r['bar.qux']`` interchangeably.
    """
    sep = ...
    def __call__(self, *args): # -> Self | Record:
        ...
    
    def __getattr__(self, name): # -> Record:
        ...
    
    def __delattr__(self, name): # -> None:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    @staticmethod
    def fromkv(k, v): # -> Record:
        ...
    
    def __getitem__(self, key): # -> Record:
        ...
    


def record(value=...): # -> Record:
    """This function returns a :class:`Record` instance constructed with an
    initial value that you provide.

    :param value: An initial record value.
    :type value: ``dict``
    """
    ...

