"""
This type stub file was generated by pyright.
"""

"""The **splunklib.utils** File for utility functions."""
def ensure_binary(s, encoding=..., errors=...): # -> bytes:
    """
    - `str` -> encoded to `bytes`
    - `bytes` -> `bytes`
    """
    ...

def ensure_str(s, encoding=..., errors=...): # -> str:
    """
    - `str` -> `str`
    - `bytes` -> decoded to `str`
    """
    ...

def assertRegex(self, *args, **kwargs): # -> Any:
    ...

