notifications:
    email: false
sudo: required

services:
    - docker

before_install:
    # Create .splunkrc file with default credentials
    - echo host=127.0.0.1 >> $HOME/.splunkrc
    - echo username=admin >> $HOME/.splunkrc
    - echo password=changed! >> $HOME/.splunkrc
    # Set SPLUNK_HOME
    - export SPLUNK_HOME="/opt/splunk"
    # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
    - sudo iptables -N DOCKER || true
    # Start docker-compose in detached mode
    - docker-compose up -d
    # Health Check (3 minutes)
    - for i in `seq 0 180`; do if docker exec -it splunk /sbin/checkstate.sh &> /dev/null; then break; fi; echo $i; sleep 1; done
    # The upload test needs to refer to a file that Splunk has in the docker
    # container
    - export INPUT_EXAMPLE_UPLOAD=$SPLUNK_HOME/var/log/splunk/splunkd_ui_access.log
    # After initial setup, we do not want to give the SDK any notion that it has
    # a local Splunk installation it can use, so we create a blank SPLUNK_HOME
    # for it, and make a placeholder for log files (which some tests generate)
    - export SPLUNK_HOME=`pwd`/splunk_home
    - mkdir -p $SPLUNK_HOME/var/log/splunk

language: python

env:
    - SPLUNK_VERSION=7.3
    - SPLUNK_VERSION=8.0

python:
  - "2.7"
  - "3.7"

install: pip install tox-travis

before_script: python setup.py build dist

script: tox
