[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "splunk-sdk"
dynamic = ["version"]
authors = [{ name = "Splunk, Inc.", email = "devinfo@splunk.com" }]
license = "Apache-2.0"
license-files = ["LICENSE"]
description = "The Splunk Software Development Kit for Python"
readme = "README.md"
dependencies = ["deprecation>=2.1.0"]
classifiers = [
    "Programming Language :: Python",
    "Development Status :: 6 - Mature",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[project.urls]
Homepage = "http://github.com/splunk/splunk-sdk-python"


[project.optional-dependencies]
dev = ["tox>=4.8.0"]

[tool.setuptools]
packages = ["splunklib", "splunklib.modularinput", "splunklib.searchcommands"]
