[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "splunk-sdk"
version = "2.1.0"
description = "The Splunk Software Development Kit for Python"
readme = "README.md"
requires-python = ">=3.7, <3.10"
license = "Apache-2.0"
# license-files = ["LICEN[CS]E.*"]
authors = [{ name = "Splunk, Inc.", email = "devinfo@splunk.com" }]
classifiers = [
  "Programming Language :: Python",
  "Development Status :: 6 - Mature",
  "Environment :: Other Environment",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
]

dependencies = ["deprecation>=2.1.0", "python-dotenv>=0.21.1"]

[dependency-groups]
dev = [
  "flake8>=3.9.2",
  "flake8-blind-except>=0.2.1",
  "flake8-builtins>=2.1.0",
  "flake8-docstrings>=1.7.0",
  "flake8-import-order>=0.19.2",
  "flake8-logging-format>=2024.24.12",
  "flake8-rst-docstrings>=0.3.0",
  "pylint>=2.13.9",
  "six>=1.17.0",
  "tox>=4.8.0",
  "twine>=4.0.2",
  "types-setuptools>=69.0.0.0",
]

[project.urls]
HOMEPAGE = "https://pypi.org/project/splunk-sdk"
DOCS = "https://docs.splunk.com/Documentation/PythonSDK/2.0.0"
REPO = "http://github.com/splunk/splunk-sdk-python.git"
