[id]
name = ai_custom_alert_app
version = 0.1.0

[package]
id = ai_custom_alert_app
check_for_updates = False

[install]
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = [EXAMPLE] AI Custom Alert App

[launcher]
description = Enrich threat intelligence using an LLM integrated with Custom Alerts
version = 0.1.0
author = Splunk
