#
version: 2.1
orbs:
  docker: circleci/docker@0.5.13
jobs:
  # here are our jobs with different Python versions
  build_splunk72:
     docker:
       - image: themattrix/tox
       - image: splunk/splunk-sdk-travis-ci:7.2-sdk
         name: splunk

     working_directory: ~/your_project
     environment:
       - SPLUNK_VERSION: 7.2-sdk
     steps:
       - checkout
       - setup_remote_docker:
          docker_layer_caching: true
       - run: apt-get update; apt-get install jq curl -y
       - docker/install-docker
       - run: echo "hello python 2.7"
        # Create .splunkrc file with default credentials
       - run: echo host=splunk >> $HOME/.splunkrc
       - run: echo username=admin >> $HOME/.splunkrc
       - run: echo password=changed! >> $HOME/.splunkrc
        # Set SPLUNK_HOME
       - run: export SPLUNK_HOME="/opt/splunk"
       - run: sudo iptables -N DOCKER || true
        # curl Splunk until it returns valid data indicating it has been setup, try 20 times maximum
       - run: for i in `seq 0 20`; do if curl --fail -k https://splunk:8089/services/server/info &> /dev/null; then break; fi; echo $i; sleep 1; done
        # The upload test needs to refer to a file that Splunk has in the docker
        # container
       - run: export INPUT_EXAMPLE_UPLOAD=$SPLUNK_HOME/var/log/splunk/splunkd_ui_access.log
        # After initial setup, we do not want to give the SDK any notion that it has
        # a local Splunk installation it can use, so we create a blank SPLUNK_HOME
        # for it, and make a placeholder for log files (which some tests generate)
       - run: export SPLUNK_HOME=`pwd`/splunk_home
       - run: mkdir -p $SPLUNK_HOME/var/log/splunk
       - run: tox
       - store_test_results:
           path: test-reports


workflows:
  version: 2
  build:
    jobs:
      - build_splunk72