[id]
name = ai_custom_search_app
version = 0.1.0

[package]
id = ai_custom_search_app
check_for_updates = False

[install]
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = [EXAMPLE] AI Custom Search Command App 

[launcher]
description = Perform custom operations on search results
version = 0.1.0
author = Splunk
