[id]
name = ai_modinput_app
version = 0.1.0

[package]
id = ai_modinput_app
check_for_updates = False

[install]
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = [EXAMPLE] AI Modular Input App

[launcher]
description = Leverage AI integrations to enrich incoming modular input data
version = 0.1.0
author = Splunk
