"""
This type stub file was generated by pyright.
"""

from collections import OrderedDict

class Configuration:
    """Defines the configuration settings for a search command.

    Documents, validates, and ensures that only relevant configuration settings are applied. Adds a :code:`name` class
    variable to search command classes that don't have one. The :code:`name` is derived from the name of the class.
    By convention command class names end with the word "Command". To derive :code:`name` the word "Command" is removed
    from the end of the class name and then converted to lower case for conformance with the `Search command style guide
    <http://docs.splunk.com/Documentation/Splunk/latest/Search/Searchcommandstyleguide>`__

    """
    def __init__(self, o=..., **kwargs) -> None:
        ...
    
    def __call__(self, o): # -> FunctionType | type[Any]:
        ...
    


class ConfigurationSetting(property):
    """Generates a :class:`property` representing the named configuration setting

    This is a convenience function designed to reduce the amount of boiler-plate code you must write; most notably for
    property setters.

    :param name: Configuration setting name.
    :type name: str or unicode

    :param doc: A documentation string.
    :type doc: bytes, unicode or NoneType

    :param readonly: If true, specifies that the configuration setting is fixed.
    :type name: bool or NoneType

    :param value: Configuration setting value.

    :return: A :class:`property` instance representing the configuration setting.
    :rtype: property

    """
    def __init__(self, fget=..., fset=..., fdel=..., doc=..., name=..., readonly=..., value=...) -> None:
        ...
    
    def __call__(self, function): # -> property:
        ...
    
    def deleter(self, function): # -> property:
        ...
    
    def getter(self, function): # -> property:
        ...
    
    def setter(self, function): # -> property:
        ...
    
    @staticmethod
    def fix_up(cls, values): # -> None:
        ...
    


class Option(property):
    """Represents a search command option.

    Required options must be specified on the search command line.

    **Example:**

    Short form (recommended). When you are satisfied with built-in or custom validation behaviors.

    ..  code-block:: python
        :linenos:

        from splunklib.searchcommands.decorators import Option
        from splunklib.searchcommands.validators import Fieldname

        total = Option(
            doc=''' **Syntax:** **total=***<fieldname>*
            **Description:** Name of the field that will hold the computed
            sum''',
            require=True, validate=Fieldname())

    **Example:**

    Long form. Useful when you wish to manage the option value and its deleter/getter/setter side-effects yourself. You
    must provide a getter and a setter. If your :code:`Option` requires `destruction <https://docs.python.org/2/reference/datamodel.html#object.__del__>`_ you must
    also provide a deleter. You must be prepared to accept a value of :const:`None` which indicates that your
    :code:`Option` is unset.

    ..  code-block:: python
        :linenos:

        from splunklib.searchcommands import Option

        @Option()
        def logging_configuration(self):
            \""" **Syntax:** logging_configuration=<path>
            **Description:** Loads an alternative logging configuration file for a command invocation. The logging
            configuration file must be in Python ConfigParser-format. The *<path>* name and all path names specified in
            configuration are relative to the app root directory.

            \"""
            return self._logging_configuration

        @logging_configuration.setter
        def logging_configuration(self, value):
            if value is not None
                logging.configure(value)
                self._logging_configuration = value

        def __init__(self)
            self._logging_configuration = None

    """
    def __init__(self, fget=..., fset=..., fdel=..., doc=..., name=..., default=..., require=..., validate=...) -> None:
        ...
    
    def __call__(self, function): # -> property:
        ...
    
    def deleter(self, function): # -> property:
        ...
    
    def getter(self, function): # -> property:
        ...
    
    def setter(self, function): # -> property:
        ...
    
    @classmethod
    def fix_up(cls, command_class): # -> None:
        ...
    
    class Item:
        """Presents an instance/class view over a search command `Option`.

        This class is used by SearchCommand.process to parse and report on option values.

        """
        def __init__(self, command, option) -> None:
            ...
        
        def __repr__(self): # -> str:
            ...
        
        def __str__(self) -> str:
            ...
        
        @property
        def is_required(self): # -> bool:
            ...
        
        @property
        def is_set(self): # -> bool:
            """Indicates whether an option value was provided as argument."""
            ...
        
        @property
        def name(self):
            ...
        
        @property
        def validator(self):
            ...
        
        @property
        def value(self):
            ...
        
        @value.setter
        def value(self, value): # -> None:
            ...
        
        def reset(self): # -> None:
            ...
        
    
    
    class View(OrderedDict):
        """Presents an ordered dictionary view of the set of :class:`Option` arguments to a search command.

        This class is used by SearchCommand.process to parse and report on option values.

        """
        def __init__(self, command) -> None:
            ...
        
        def __repr__(self): # -> str:
            ...
        
        def __str__(self) -> str:
            ...
        
        def get_missing(self): # -> list[Any] | None:
            ...
        
        def reset(self): # -> None:
            ...
        
    
    


__all__ = ["Configuration", "Option"]
