"""
This type stub file was generated by pyright.
"""

from .search_command import SearchCommand

class EventingCommand(SearchCommand):
    """Applies a transformation to search results as they travel through the events pipeline.

    Eventing commands typically filter, group, order, and/or or augment event records. Examples of eventing commands
    from Splunk's built-in command set include sort_, dedup_, and cluster_. Each execution of an eventing command
    should produce a set of event records that is independently usable by downstream processors.

    .. _sort: http://docs.splunk.com/Documentation/Splunk/latest/SearchReference/Sort
    .. _dedup: http://docs.splunk.com/Documentation/Splunk/latest/SearchReference/Dedup
    .. _cluster: http://docs.splunk.com/Documentation/Splunk/latest/SearchReference/Cluster

    EventingCommand configuration
    ==============================

    You can configure your command for operation under Search Command Protocol (SCP) version 1 or 2. SCP 2 requires
    Splunk 6.3 or later.

    """
    def transform(self, records):
        """Generator function that processes and yields event records to the Splunk events pipeline.

        You must override this method.

        """
        ...
    
    class ConfigurationSettings(SearchCommand.ConfigurationSettings):
        """Represents the configuration settings that apply to a :class:`EventingCommand`."""
        required_fields = ...
        clear_required_fields = ...
        retainsevents = ...
        maxinputs = ...
        type = ...
        @classmethod
        def fix_up(cls, command): # -> None:
            """Verifies :code:`command` class structure."""
            ...
        
        def iteritems(self): # -> list[tuple[Any, Any | str]]:
            ...
        
        items = ...
    
    


