"""
This type stub file was generated by pyright.
"""

import sys

if sys.platform == "win32":
    ...
class ExternalSearchCommand:
    def __init__(self, path, argv=..., environ=...) -> None:
        ...
    
    @property
    def argv(self): # -> Any:
        ...
    
    @argv.setter
    def argv(self, value): # -> None:
        ...
    
    @property
    def environ(self): # -> Any:
        ...
    
    @environ.setter
    def environ(self, value): # -> None:
        ...
    
    @property
    def logger(self): # -> Logger:
        ...
    
    @property
    def path(self): # -> str:
        ...
    
    def execute(self): # -> None:
        ...
    
    if sys.platform == "win32":
        _executable_extensions = ...
    else:
        ...


def execute(path, argv=..., environ=..., command_class=...): # -> None:
    """
    :param path:
    :type path: basestring
    :param argv:
    :type: argv: list, tuple, or None
    :param environ:
    :type environ: dict
    :param command_class: External search command class to instantiate and execute.
    :type command_class: type
    :return:
    :rtype: None
    """
    ...

