"""
This type stub file was generated by pyright.
"""

import csv
import sys
from json import JSONDecoder, JSONEncoder

def set_binary_mode(fh): # -> _WrappedBuffer | TextIOWrapper[_WrappedBuffer]:
    """Helper method to set up binary mode for file handles.
    Emphasis being sys.stdin, sys.stdout, sys.stderr.
    For python3, we want to return .buffer
    """
    ...

class CommandLineParser:
    r"""Parses the arguments to a search command.

    A search command line is described by the following syntax.

    **Syntax**::

       command       = command-name *[wsp option] *[wsp [dquote] field-name [dquote]]
       command-name  = alpha *( alpha / digit )
       option        = option-name [wsp] "=" [wsp] option-value
       option-name   = alpha *( alpha / digit / "_" )
       option-value  = word / quoted-string
       word          = 1*( %01-%08 / %0B / %0C / %0E-1F / %21 / %23-%FF ) ; Any character but DQUOTE and WSP
       quoted-string = dquote *( word / wsp / "\" dquote / dquote dquote ) dquote
       field-name    = ( "_" / alpha ) *( alpha / digit / "_" / "." / "-" )

    **Note:**

    This syntax is constrained to an 8-bit character set.

    **Note:**

    This syntax does not show that `field-name` values may be comma-separated when in fact they can be. This is
    because Splunk strips commas from the command line. A custom search command will never see them.

    **Example:**

    countmatches fieldname = word_count pattern = \w+ some_text_field

    Option names are mapped to properties in the targeted ``SearchCommand``. It is the responsibility of the property
    setters to validate the values they receive. Property setters may also produce side effects. For example,
    setting the built-in `log_level` immediately changes the `log_level`.

    """
    @classmethod
    def parse(cls, command, argv): # -> None:
        """Splits an argument list into an options dictionary and a fieldname
        list.

        The argument list, `argv`, must be of the form::

            *[option]... *[<field-name>]

        Options are validated and assigned to items in `command.options`. Field names are validated and stored in the
        list of `command.fieldnames`.

        #Arguments:

        :param command: Search command instance.
        :type command: ``SearchCommand``
        :param argv: List of search command arguments.
        :type argv: ``list``
        :return: ``None``

        #Exceptions:

        ``SyntaxError``: Argument list is incorrectly formed.
        ``ValueError``: Unrecognized option/field name, or an illegal field value.

        """
        ...
    
    @classmethod
    def unquote(cls, string): # -> str:
        """Removes quotes from a quoted string.

        Splunk search command quote rules are applied. The enclosing double-quotes, if present, are removed. Escaped
        double-quotes ('\"' or '""') are replaced by a single double-quote ('"').

        **NOTE**

        We are not using a json.JSONDecoder because Splunk quote rules are different than JSON quote rules. A
        json.JSONDecoder does not recognize a pair of double-quotes ('""') as an escaped quote ('"') and will
        decode single-quoted strings ("'") in addition to double-quoted ('"') strings.

        """
        ...
    
    _arguments_re = ...
    _escaped_character_re = ...
    _fieldnames_re = ...
    _options_re = ...


class ConfigurationSettingsType(type):
    """Metaclass for constructing ConfigurationSettings classes.

    Instances of :class:`ConfigurationSettingsType` construct :class:`ConfigurationSettings` classes from classes from
    a base :class:`ConfigurationSettings` class and a dictionary of configuration settings. The settings in the
    dictionary are validated against the settings in the base class. You cannot add settings, you can only change their
    backing-field values and you cannot modify settings without backing-field values. These are considered fixed
    configuration setting values.

    This is an internal class used in two places:

    + :meth:`decorators.Configuration.__call__`

      Adds a ConfigurationSettings attribute to a :class:`SearchCommand` class.

    + :meth:`reporting_command.ReportingCommand.fix_up`

      Adds a ConfigurationSettings attribute to a :meth:`ReportingCommand.map` method, if there is one.

    """
    def __new__(mcs, module, name, bases): # -> Self:
        ...
    
    def __init__(cls, module, name, bases) -> None:
        ...
    
    @staticmethod
    def validate_configuration_setting(specification, name, value):
        ...
    
    specification = ...
    specification_matrix = ...


class CsvDialect(csv.Dialect):
    """Describes the properties of Splunk CSV streams"""
    delimiter = ...
    quotechar = ...
    doublequote = ...
    skipinitialspace = ...
    lineterminator = ...
    if sys.version_info >= (3, 0) and sys.platform == "win32":
        lineterminator = ...
    quoting = ...


class InputHeader(dict):
    """Represents a Splunk input header as a collection of name/value pairs."""
    def __str__(self) -> str:
        ...
    
    def read(self, ifile): # -> None:
        """Reads an input header from an input file.

        The input header is read as a sequence of *<name>***:***<value>* pairs separated by a newline. The end of the
        input header is signalled by an empty line or an end-of-file.

        :param ifile: File-like object that supports iteration over lines.

        """
        ...
    


Message = ...
class MetadataDecoder(JSONDecoder):
    def __init__(self) -> None:
        ...
    


class MetadataEncoder(JSONEncoder):
    def __init__(self) -> None:
        ...
    
    def default(self, o): # -> dict[str, Any] | Any:
        ...
    
    _separators = ...


class ObjectView:
    def __init__(self, dictionary) -> None:
        ...
    
    def update(self, obj): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class Recorder:
    def __init__(self, path, f) -> None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def read(self, size=...):
        ...
    
    def readline(self, size=...):
        ...
    
    def record(self, *args): # -> None:
        ...
    
    def write(self, text): # -> None:
        ...
    


class RecordWriter:
    def __init__(self, ofile, maxresultrows=...) -> None:
        ...
    
    @property
    def is_flushed(self): # -> bool:
        ...
    
    @is_flushed.setter
    def is_flushed(self, value): # -> None:
        ...
    
    @property
    def ofile(self): # -> Any | _WrappedBuffer | TextIOWrapper[_WrappedBuffer]:
        ...
    
    @ofile.setter
    def ofile(self, value): # -> None:
        ...
    
    @property
    def pending_record_count(self): # -> int:
        ...
    
    @property
    def committed_record_count(self): # -> int:
        ...
    
    def write(self, data): # -> None:
        ...
    
    def flush(self, finished=..., partial=...): # -> None:
        ...
    
    def write_message(self, message_type, message_text, *args, **kwargs): # -> None:
        ...
    
    def write_record(self, record): # -> None:
        ...
    
    def write_records(self, records): # -> None:
        ...
    


class RecordWriterV1(RecordWriter):
    def flush(self, finished=..., partial=...): # -> None:
        ...
    
    _message_level = ...


class RecordWriterV2(RecordWriter):
    def flush(self, finished=..., partial=...): # -> None:
        ...
    
    def write_chunk(self, finished=...): # -> None:
        ...
    
    def write_metadata(self, configuration): # -> None:
        ...
    
    def write_metric(self, name, value): # -> None:
        ...
    


