"""
This type stub file was generated by pyright.
"""

from . import Option

class SearchCommand:
    """Represents a custom search command."""
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @Option
    def logging_configuration(self): # -> str | None:
        """**Syntax:** logging_configuration=<path>

        **Description:** Loads an alternative logging configuration file for
        a command invocation. The logging configuration file must be in Python
        ConfigParser-format. Path names are relative to the app root directory.

        """
        ...
    
    @logging_configuration.setter
    def logging_configuration(self, value): # -> None:
        ...
    
    @Option
    def logging_level(self): # -> str:
        """**Syntax:** logging_level=[CRITICAL|ERROR|WARNING|INFO|DEBUG|NOTSET]

        **Description:** Sets the threshold for the logger of this command invocation. Logging messages less severe than
        `logging_level` will be ignored.

        """
        ...
    
    @logging_level.setter
    def logging_level(self, value): # -> None:
        ...
    
    def add_field(self, current_record, field_name, field_value): # -> None:
        ...
    
    def gen_record(self, **record): # -> dict[str, Any]:
        ...
    
    record = ...
    show_configuration = ...
    @property
    def configuration(self): # -> ConfigurationSettings:
        """Returns the configuration settings for this command."""
        ...
    
    @property
    def fieldnames(self): # -> None:
        """Returns the fieldnames specified as argument to this command."""
        ...
    
    @fieldnames.setter
    def fieldnames(self, value): # -> None:
        ...
    
    @property
    def input_header(self): # -> InputHeader:
        """Returns the input header for this command.

        :return: The input header for this command.
        :rtype: InputHeader

        """
        ...
    
    @property
    def logger(self): # -> Logger | None:
        """Returns the logger for this command.

        :return: The logger for this command.
        :rtype:

        """
        ...
    
    @property
    def metadata(self): # -> ObjectView | Any | None:
        ...
    
    @property
    def options(self): # -> View:
        """Returns the options specified as argument to this command."""
        ...
    
    @property
    def protocol_version(self): # -> int | None:
        ...
    
    @property
    def search_results_info(self): # -> ObjectView | None:
        """Returns the search results info for this command invocation.

        The search results info object is created from the search results info file associated with the command
        invocation.

        :return: Search results info:const:`None`, if the search results info file associated with the command
                 invocation is inaccessible.
        :rtype: SearchResultsInfo or NoneType

        """
        ...
    
    @property
    def service(self): # -> Service | None:
        """Returns a Splunk service object for this command invocation or None.

        The service object is created from the Splunkd URI and authentication token passed to the command invocation in
        the search results info file. This data is not passed to a command invocation by default. You must request it by
        specifying this pair of configuration settings in commands.conf:

           .. code-block:: python

               enableheader = true
               requires_srinfo = true

        The :code:`enableheader` setting is :code:`true` by default. Hence, you need not set it. The
        :code:`requires_srinfo` setting is false by default. Hence, you must set it.

        :return: :class:`splunklib.client.Service`, if :code:`enableheader` and :code:`requires_srinfo` are both
            :code:`true`. Otherwise, if either :code:`enableheader` or :code:`requires_srinfo` are :code:`false`, a value
            of :code:`None` is returned.

        """
        ...
    
    def error_exit(self, error, message=...):
        ...
    
    def finish(self): # -> None:
        """Flushes the output buffer and signals that this command has finished processing data.

        :return: :const:`None`

        """
        ...
    
    def flush(self): # -> None:
        """Flushes the output buffer.

        :return: :const:`None`

        """
        ...
    
    def prepare(self): # -> None:
        """Prepare for execution.

        This method should be overridden in search command classes that wish to examine and update their configuration
        or option settings prior to execution. It is called during the getinfo exchange before command metadata is sent
        to splunkd.

        :return: :const:`None`
        :rtype: NoneType

        """
        ...
    
    def process(self, argv=..., ifile=..., ofile=..., allow_empty_input=...): # -> None:
        """Process data.

        :param argv: Command line arguments.
        :type argv: list or tuple

        :param ifile: Input data file.
        :type ifile: file

        :param ofile: Output data file.
        :type ofile: file

        :param allow_empty_input: Allow empty input records for the command, if False an Error will be returned if empty chunk body is encountered when read
        :type allow_empty_input: bool

        :return: :const:`None`
        :rtype: NoneType

        """
        ...
    
    _metadata_map = ...
    _MetadataSource = ...
    def write_debug(self, message, *args): # -> None:
        ...
    
    def write_error(self, message, *args): # -> None:
        ...
    
    def write_fatal(self, message, *args): # -> None:
        ...
    
    def write_info(self, message, *args): # -> None:
        ...
    
    def write_warning(self, message, *args): # -> None:
        ...
    
    def write_metric(self, name, value): # -> None:
        """Writes a metric that will be added to the search inspector.

        :param name: Name of the metric.
        :type name: basestring

        :param value: A 4-tuple containing the value of metric ``name`` where

            value[0] = Elapsed seconds or :const:`None`.
            value[1] = Number of invocations or :const:`None`.
            value[2] = Input count or :const:`None`.
            value[3] = Output count or :const:`None`.

        The :data:`SearchMetric` type provides a convenient encapsulation of ``value``.
        The :data:`SearchMetric` type provides a convenient encapsulation of ``value``.

        :return: :const:`None`.

        """
        ...
    
    _encoded_value = ...
    _header = ...
    class ConfigurationSettings:
        """Represents the configuration settings common to all :class:`SearchCommand` classes."""
        def __init__(self, command) -> None:
            ...
        
        def __repr__(self): # -> str:
            """Converts the value of this instance to its string representation.

            The value of this ConfigurationSettings instance is represented as a string of comma-separated
            :code:`(name, value)` pairs.

            :return: String representation of this instance

            """
            ...
        
        def __str__(self) -> str:
            """Converts the value of this instance to its string representation.

            The value of this ConfigurationSettings instance is represented as a string of comma-separated
            :code:`name=value` pairs. Items with values of :const:`None` are filtered from the list.

            :return: String representation of this instance

            """
            ...
        
        @classmethod
        def fix_up(cls, command_class): # -> None:
            """Adjusts and checks this class and its search command class.

            Derived classes typically override this method. It is used by the :decorator:`Configuration` decorator to
            fix up the :class:`SearchCommand` class it adorns. This method is overridden by :class:`EventingCommand`,
            :class:`GeneratingCommand`, :class:`ReportingCommand`, and :class:`StreamingCommand`, the base types for
            all other search commands.

            :param command_class: Command class targeted by this class

            """
            ...
        
        def iteritems(self): # -> list[tuple[Any, Any]]:
            ...
        
        items = ...
    
    


SearchMetric = ...
def dispatch(command_class, argv=..., input_file=..., output_file=..., module_name=..., allow_empty_input=...): # -> None:
    """Instantiates and executes a search command class

    This function implements a `conditional script stanza <https://docs.python.org/2/library/__main__.html>`_ based on the value of
    :code:`module_name`::

        if module_name is None or module_name == '__main__':
            # execute command

    Call this function at module scope with :code:`module_name=__name__`, if you would like your module to act as either
    a reusable module or a standalone program. Otherwise, if you wish this function to unconditionally instantiate and
    execute :code:`command_class`, pass :const:`None` as the value of :code:`module_name`.

    :param command_class: Search command class to instantiate and execute.
    :type command_class: type
    :param argv: List of arguments to the command.
    :type argv: list or tuple
    :param input_file: File from which the command will read data.
    :type input_file: :code:`file`
    :param output_file: File to which the command will write data.
    :type output_file: :code:`file`
    :param module_name: Name of the module calling :code:`dispatch` or :const:`None`.
    :type module_name: :code:`basestring`
    :param allow_empty_input: Allow empty input records for the command, if False an Error will be returned if empty chunk body is encountered when read
    :type allow_empty_input: bool
    :returns: :const:`None`

    **Example**

    ..  code-block:: python
        :linenos:

        #!/usr/bin/env python
        from splunklib.searchcommands import dispatch, StreamingCommand, Configuration, Option, validators
        @Configuration()
        class SomeStreamingCommand(StreamingCommand):
            ...
            def stream(records):
                ...
        dispatch(SomeStreamingCommand, module_name=__name__)

    Dispatches the :code:`SomeStreamingCommand`, if and only if :code:`__name__` is equal to :code:`'__main__'`.

    **Example**

    ..  code-block:: python
        :linenos:

        from splunklib.searchcommands import dispatch, StreamingCommand, Configuration, Option, validators
        @Configuration()
        class SomeStreamingCommand(StreamingCommand):
            ...
            def stream(records):
                ...
        dispatch(SomeStreamingCommand)

    Unconditionally dispatches :code:`SomeStreamingCommand`.

    """
    ...

