"""
This type stub file was generated by pyright.
"""

from .search_command import SearchCommand

class StreamingCommand(SearchCommand):
    """Applies a transformation to search results as they travel through the streams pipeline.

    Streaming commands typically filter, augment, or update, search result records. Splunk will send them in batches of
    up to 50,000 records. Hence, a search command must be prepared to be invoked many times during the course of
    pipeline processing. Each invocation should produce a set of results independently usable by downstream processors.

    By default Splunk may choose to run a streaming command locally on a search head and/or remotely on one or more
    indexers concurrently. The size and frequency of the search result batches sent to the command will vary based
    on scheduling considerations.

    StreamingCommand configuration
    ==============================

    You can configure your command for operation under Search Command Protocol (SCP) version 1 or 2. SCP 2 requires
    Splunk 6.3 or later.

    """
    def stream(self, records):
        """Generator function that processes and yields event records to the Splunk stream pipeline.

        You must override this method.

        """
        ...
    
    class ConfigurationSettings(SearchCommand.ConfigurationSettings):
        """Represents the configuration settings that apply to a :class:`StreamingCommand`."""
        required_fields = ...
        clear_required_fields = ...
        local = ...
        overrides_timeorder = ...
        streaming = ...
        distributed = ...
        maxinputs = ...
        type = ...
        @classmethod
        def fix_up(cls, command): # -> None:
            """Verifies :code:`command` class structure."""
            ...
        
        def iteritems(self): # -> list[tuple[Any, Any]] | list[tuple[str, str] | tuple[Any, Any]]:
            ...
        
        items = ...
    
    


