"""
This type stub file was generated by pyright.
"""

import csv

class Validator:
    """Base class for validators that check and format search command options.

    You must inherit from this class and override :code:`Validator.__call__` and
    :code:`Validator.format`. :code:`Validator.__call__` should convert the
    value it receives as argument and then return it or raise a
    :code:`ValueError`, if the value will not convert.

    :code:`Validator.format` should return a human readable version of the value
    it receives as argument the same way :code:`str` does.

    """
    def __call__(self, value):
        ...
    
    def format(self, value):
        ...
    


class Boolean(Validator):
    """Validates Boolean option values."""
    truth_values = ...
    def __call__(self, value): # -> bool:
        ...
    
    def format(self, value): # -> Literal['t', 'f'] | None:
        ...
    


class Code(Validator):
    """Validates code option values.

    This validator compiles an option value into a Python code object that can be executed by :func:`exec` or evaluated
    by :func:`eval`. The value returned is a :func:`namedtuple` with two members: object, the result of compilation, and
    source, the original option value.

    """
    def __init__(self, mode=...) -> None:
        """
        :param mode: Specifies what kind of code must be compiled; it can be :const:`'exec'`, if source consists of a
            sequence of statements, :const:`'eval'`, if it consists of a single expression, or :const:`'single'` if it
            consists of a single interactive statement. In the latter case, expression statements that evaluate to
            something other than :const:`None` will be printed.
        :type mode: unicode or bytes

        """
        ...
    
    def __call__(self, value): # -> Code | None:
        ...
    
    def format(self, value): # -> None:
        ...
    
    object = ...


class Fieldname(Validator):
    """Validates field name option values."""
    pattern = ...
    def __call__(self, value): # -> str:
        ...
    
    def format(self, value):
        ...
    


class File(Validator):
    """Validates file option values."""
    def __init__(self, mode=..., buffering=..., directory=...) -> None:
        ...
    
    def __call__(self, value): # -> IO[Any]:
        ...
    
    def format(self, value): # -> None:
        ...
    
    _var_run_splunk = ...


class Integer(Validator):
    """Validates integer option values."""
    def __init__(self, minimum=..., maximum=...) -> None:
        ...
    
    def __call__(self, value): # -> int | None:
        ...
    
    def format(self, value): # -> str | None:
        ...
    


class Float(Validator):
    """Validates float option values."""
    def __init__(self, minimum=..., maximum=...) -> None:
        ...
    
    def __call__(self, value): # -> float | None:
        ...
    
    def format(self, value): # -> str | None:
        ...
    


class Duration(Validator):
    """Validates duration option values."""
    def __call__(self, value): # -> int | None:
        ...
    
    def format(self, value): # -> str | None:
        ...
    
    _60 = ...
    _unsigned = ...


class List(Validator):
    """Validates a list of strings"""
    class Dialect(csv.Dialect):
        """Describes the properties of list option values."""
        strict = ...
        delimiter = ...
        quotechar = ...
        doublequote = ...
        lineterminator = ...
        skipinitialspace = ...
        quoting = ...
    
    
    def __init__(self, validator=...) -> None:
        ...
    
    def __call__(self, value): # -> list[Any] | list[str]:
        ...
    
    def format(self, value): # -> str:
        ...
    


class Map(Validator):
    """Validates map option values."""
    def __init__(self, **kwargs) -> None:
        ...
    
    def __call__(self, value): # -> None:
        ...
    
    def format(self, value): # -> str | None:
        ...
    


class Match(Validator):
    """Validates that a value matches a regular expression pattern."""
    def __init__(self, name, pattern, flags=...) -> None:
        ...
    
    def __call__(self, value): # -> str | None:
        ...
    
    def format(self, value): # -> str | None:
        ...
    


class OptionName(Validator):
    """Validates option names."""
    pattern = ...
    def __call__(self, value): # -> str:
        ...
    
    def format(self, value): # -> str | None:
        ...
    


class RegularExpression(Validator):
    """Validates regular expression option values."""
    def __call__(self, value): # -> Pattern[str] | None:
        ...
    
    def format(self, value): # -> None:
        ...
    


class Set(Validator):
    """Validates set option values."""
    def __init__(self, *args) -> None:
        ...
    
    def __call__(self, value): # -> str | None:
        ...
    
    def format(self, value): # -> str | None:
        ...
    


__all__ = ["Boolean", "Code", "Duration", "File", "Integer", "Float", "List", "Map", "RegularExpression", "Set"]
