"""
This type stub file was generated by pyright.
"""

from .argument import Argument
from .event import Event
from .event_writer import EventWriter
from .input_definition import InputDefinition
from .scheme import Scheme
from .script import Script
from .validation_definition import ValidationDefinition

"""The following imports allow these classes to be imported via
the splunklib.modularinput package like so:

from splunklib.modularinput import *
"""
