"""
This type stub file was generated by pyright.
"""

class EventWriter:
    """``EventWriter`` writes events and error messages to Splunk from a modular input.
    Its two important methods are ``writeEvent``, which takes an ``Event`` object,
    and ``log``, which takes a severity and an error message.
    """
    DEBUG = ...
    INFO = ...
    WARN = ...
    ERROR = ...
    FATAL = ...
    def __init__(self, output=..., error=...) -> None:
        """
        :param output: Where to write the output; defaults to sys.stdout.
        :param error: Where to write any errors; defaults to sys.stderr.
        """
        ...
    
    def write_event(self, event): # -> None:
        """Writes an ``Event`` object to Splunk.

        :param event: An ``Event`` object.
        """
        ...
    
    def log(self, severity, message): # -> None:
        """Logs messages about the state of this modular input to Splunk.
        These messages will show up in Splunk's internal logs.

        :param severity: ``string``, severity of message, see severities defined as class constants.
        :param message: ``string``, message to log.
        """
        ...
    
    def log_exception(self, message, exception=..., severity=...): # -> None:
        """Logs messages about the exception thrown by this modular input to Splunk.
        These messages will show up in Splunk's internal logs.

        :param message: ``string``, message to log.
        :param exception: ``Exception``, exception thrown by this modular input; if none, sys.exc_info() is used
        :param severity: ``string``, severity of message, see severities defined as class constants. Default severity: ERROR
        """
        ...
    
    def write_xml_document(self, document): # -> None:
        """Writes a string representation of an
        ``ElementTree`` object to the output stream.

        :param document: An ``ElementTree`` object.
        """
        ...
    
    def close(self): # -> None:
        """Write the closing </stream> tag to make this XML well formed."""
        ...
    


