"""
This type stub file was generated by pyright.
"""

class InputDefinition:
    """``InputDefinition`` encodes the XML defining inputs that Splunk passes to
    a modular input script.

     **Example**::

        i = InputDefinition()

    """
    def __init__(self) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    @staticmethod
    def parse(stream): # -> InputDefinition:
        """Parse a stream containing XML into an ``InputDefinition``.

        :param stream: stream containing XML to parse.
        :return: definition: an ``InputDefinition`` object.
        """
        ...
    


