"""
This type stub file was generated by pyright.
"""

class Scheme:
    """Class representing the metadata for a modular input kind.

    A ``Scheme`` specifies a title, description, several options of how Splunk should run modular inputs of this
    kind, and a set of arguments which define a particular modular input's properties.

    The primary use of ``Scheme`` is to abstract away the construction of XML to feed to Splunk.
    """
    streaming_mode_simple = ...
    streaming_mode_xml = ...
    def __init__(self, title) -> None:
        """
        :param title: ``string`` identifier for this Scheme in Splunk.
        """
        ...
    
    def add_argument(self, arg): # -> None:
        """Add the provided argument, ``arg``, to the ``self.arguments`` list.

        :param arg: An ``Argument`` object to add to ``self.arguments``.
        """
        ...
    
    def to_xml(self): # -> Element[str]:
        """Creates an ``ET.Element`` representing self, then returns it.

        :returns: an ``ET.Element`` representing this scheme.
        """
        ...
    


