"""
This type stub file was generated by pyright.
"""

def xml_compare(expected, found): # -> bool:
    """Checks equality of two ``ElementTree`` objects.

    :param expected: An ``ElementTree`` object.
    :param found: An ``ElementTree`` object.
    :return: ``Boolean``, whether the two objects are equal.
    """
    ...

def parse_parameters(param_node): # -> list[Any]:
    ...

def parse_xml_data(parent_node, child_node_tag): # -> dict[Any, Any]:
    ...

