"""
This type stub file was generated by pyright.
"""

class ValidationDefinition:
    """This class represents the XML sent by Splunk for external validation of a
    new modular input.

    **Example**::

        v = ValidationDefinition()

    """
    def __init__(self) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    @staticmethod
    def parse(stream): # -> ValidationDefinition:
        """Creates a ``ValidationDefinition`` from a provided stream containing XML.

        The XML typically will look like this:

        ..  code-block:: xml

            <items>
               <server_host>myHost</server_host>
                 <server_uri>https://127.0.0.1:8089</server_uri>
                 <session_key>123102983109283019283</session_key>
                 <checkpoint_dir>/opt/splunk/var/lib/splunk/modinputs</checkpoint_dir>
                 <item name="myScheme">
                   <param name="param1">value1</param>
                   <param_list name="param2">
                     <value>value2</value>
                     <value>value3</value>
                     <value>value4</value>
                   </param_list>
                 </item>
            </items>

        :param stream: ``Stream`` containing XML to parse.
        :return: A ``ValidationDefinition`` object.

        """
        ...
    


