# -*- coding: utf-8 -*-
# Copyright 2011-2013 Splunk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"): you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from splunklib.modularinput.modularinput_testlib import unittest, xml_compare
from splunklib.modularinput.scheme import Scheme
from splunklib.modularinput.argument import Argument

try:
    import xml.etree.cElementTree as ET
except ImportError:
    import xml.etree.ElementTree as ET

class SchemeTest(unittest.TestCase):
    def test_generate_xml_from_scheme_with_default_values(self):
        """Checks the Scheme generated by creating a Scheme object and setting no fields on it.
        This test checks for sane defaults in the class."""

        scheme = Scheme("abcd")

        constructed = scheme.toXML()
        expected = ET.parse(open("data/scheme_with_defaults.xml")).getroot()

        self.assertTrue(xml_compare(expected, constructed))

    def test_generate_xml_from_scheme(self):
        """Checks that the XML generated by a Scheme object with all its fields set and
        some arguments added matches what we expect."""

        #todo: change argument constructor to take keyword args

        scheme = Scheme("abcd")
        scheme.description = u"쎼 and 쎶 and <&> für"
        scheme.streamingMode = scheme.streamingModeSimple
        scheme.useExternalValidation = "false"
        scheme.useSingleInstance = "true"

        arg1 = Argument("arg1")
        scheme.addArgument(arg1)

        arg2 = Argument("arg2")
        arg2.description = u"쎼 and 쎶 and <&> für"
        arg2.dataType = arg2.dataTypeNumber
        arg2.requiredOnCreate = "true"
        arg2.requiredOnEdit = "true"
        arg2.validation = "is_pos_int('some_name')"
        scheme.addArgument(arg2)

        constructed = scheme.toXML()
        expected = ET.parse(open("data/scheme_without_defaults.xml")).getroot()

        self.assertTrue(xml_compare(expected, constructed))

    def test_generate_xml_from_argument_with_default_values(self):
        """Checks that the XML produced from an Argument class that is initialized but has no additional manipulations
        made to it is what we expect. This is mostly a check of the default values."""

        argument = Argument("some_name")

        root = ET.Element("")
        constructed = argument.addToDocument(root)

        expected = ET.parse(open("data/argument_with_defaults.xml")).getroot()

        self.assertTrue(xml_compare(expected, constructed))

    def test_generate_xml_from_argument(self):
        """Checks that the XML generated by an Argument class with all its possible values set is what we expect."""
        argument = Argument("some_name")
        argument.description = u"쎼 and 쎶 and <&> für"
        argument.dataType = argument.dataTypeBoolean
        argument.validation = "is_pos_int('some_name')"
        argument.requiredOnEdit = "true"
        argument.requiredOnCreate = "true"

        root = ET.Element("")
        constructed = argument.addToDocument(root)

        expected = ET.parse(open("data/argument_without_defaults.xml")).getroot()

        self.assertTrue(xml_compare(expected, constructed))

if __name__ == "__main__":
    unittest.main()