name: Validate SDK with Splunk AppInspect
on:
  push:
    branches: [develop, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  appinspect:
    name: Run AppInspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-sdk-environment
        with:
          deps-group: lint
      - name: Run AppInspect
        uses: ./.github/actions/run-appinspect
