name: Validate SDK with Splunk AppInspect
on:
  push:
    branches: [develop, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  PYTHON_VERSION: 3.13

jobs:
  appinspect:
    name: Run AppInspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-sdk-environment
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          deps-group: lint
      - name: Run AppInspect
        uses: ./.github/actions/run-appinspect
