name: Python SDK Lint
on:
  push:
    branches: [develop, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-sdk-environment
        with:
          python-version: ${{ matrix.python-version }}
          deps-group: lint
      - name: Verify uv.lock is up-to-date
        run: uv lock --check
      - name: Verify files are linted and formatted
        run: make ci-lint
