name: Python SDK Lint
on: [push, workflow_dispatch]

env:
  PYTHON_VERSION: 3.9

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/setup-sdk-environment
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          deps-group: lint
      - name: Verify uv.lock is up-to-date
        run: uv lock --check
      - name: Verify against basedpyright baseline
        run: uv run --frozen basedpyright
