name: Python SDK CI
on: [push, workflow_dispatch]

jobs:
  lint-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: astral-sh/setup-uv@0acf9708cec26cdcd463dd57db30a4eb5b123bda
        with:
          activate-environment: true
      - name: Verify uv.lock is up-to-date
        run: uv lock --check
      - name: Install dependencies with uv
        run: uv sync
      - name: Verify basedpyright baseline
        run: uv run --frozen basedpyright
