name: Publish SDK to Test PyPI
on: [workflow_dispatch]

env:
  PYTHON_VERSION: 3.9

jobs:
  publish-sdk-test-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: splunk-test-pypi
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: python -m pip install . --group build
      - name: Build packages for distribution
        run: python -m build
      - name: Publish packages to Test PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          repository-url: https://test.pypi.org/legacy/
