name: Publish SDK to PyPI
on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.9

jobs:
  publish-sdk-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: splunk-pypi
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: python -m pip install . --group release
      - name: Build packages for distribution
        run: python -m build
      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
      - name: Generate API reference
        run: make -C ./docs html
      - name: Upload docs artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: python-sdk-docs
          path: docs/_build/html
