name: Python CI
on: [push, workflow_dispatch]

jobs:
  run-test-suite:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        splunk-version: [9.4, latest]
        include:
          # Oldest possible configuration
          # Last Ubuntu version with Python 3.7 binaries available
          - os: ubuntu-22.04
            python-version: 3.7
            splunk-version: 9.1
          # Latest possible configuration
          - os: ubuntu-latest
            python-version: 3.13
            splunk-version: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Launch Splunk Docker instance
        run: SPLUNK_VERSION=${{ matrix.splunk-version }} docker compose up -d
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.python-version }}
      - name: (Python 3.7) Install dependencies
        if: ${{ matrix.python-version == '3.7' }}
        run: python -m pip install python-dotenv pytest
      - name: (Python >= 3.9) Install dependencies
        if: ${{ matrix.python-version != '3.7' }}
        run: python -m pip install . --group test
      - name: Run entire test suite
        run: python -m pytest ./tests
